# Generated by Django 3.1.4 on 2021-09-18 17:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('Phone_Number', models.IntegerField(unique=True)),
                ('Account_Number', models.UUIDField(default=uuid.uuid4)),
                ('Bank_Name', models.CharField(max_length=100)),
                ('Branch_Name', models.CharField(max_length=100)),
                ('Montly_Income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DOB', models.DateField()),
                ('Nationality', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('health_Insurance', models.BooleanField(default=False)),
                ('Life_Insurance', models.BooleanField(default=False)),
                ('Profession', models.CharField(max_length=100)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
