# Generated by Django 3.1.4 on 2021-09-29 10:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Account_Number',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
